version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: pixel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pixellive
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes: # 데이터 영구 저장을 위해 추가
      - ./db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: pixel-redis
    ports:
      - "6379:6379"
